### ISSUE TITLE
Doesn't work in my Neovim

### ISSUE THREAD

**Issue by brianhuster** [alexxGmZ/player.nvim#3]
I am using NVIM v0.11.0-dev-1108+g5a86360400. The problem is that player.nvim doesn't work with my Spotify. I try all Player commands, and it just returns "stopped", while my playerctl can still control that  Spotify, it does work when I run `playerctl play-pause`. 

This is my config for the plugin. Nothing special, I think
```lua
return {
	"alexxGmZ/player.nvim",
	config = true
}
```
Oh, and my Spotify was installed from snap

**Comment by alexxGmZ** [comment]
Open spotify and see if it is included in `playerctl -l`.

Also have you tried specifying spotify?
`:Player spotify <command>`

**Comment by brianhuster** [comment]
This is the output of `playerctl -l` when I open Spotify
```
edge.instance2
spotify
```
Yes, I have tried 
```vim
:Player spotify play-pause
```
And it doesn't work

But if I run in the terminal
```sh
playerctl play-pause
```
It **does** work

**Comment by brianhuster** [comment]
Btw, I found the reason. Although I can control the player from terminal, yes `playerctl play-pause` does work with continuing-pausing my spotify, But I realize `player status` still return `Stopped` even though my Spotify is running.

So I think your plugin is overcomplicated. It is just a wrapper about `playerctl` commandline, right, so why does it need to check status before executing my command. When I type `:Player play-pause`, why doesn't it just send the command `playerctl play-pause` to the shell? Why does it need to check `playerctl status` before running the command I want to run?

**Comment by alexxGmZ** [comment]
I installed Spotify the flatpak version and you're right it's not working. When I am developing this plugin I was using the .deb version (installed it through `apt`). So I guess it has something to do with that.

I also noticed that it doesn't work if there are more than 2 media players are open, especially if the first player in `playerctl` like in your case is `edge` assuming it is Microsoft Edge is considered a `Stopped` status.

Anyways thanks for the heads up, I'll try to fix it.

**Comment by alexxGmZ** [comment]
Fixed it now (I hope LOL).

<br>

> Why does it need to check playerctl status before running the command I want to run?.

Hmmm... I think back then I just want to see the nvim-notify says `Stopped`. And since it is a shell command I feel like it is too **dangerous** to let it run easily, an irrational fear I guess.

Anyways I'm closing this issue.

**Comment by phambinhanctb** [comment]
Yes, it's an irrational fear. Your plugin can't be any more dangerous than just running shell command with `:!` in Nvim cmdline

**Comment by brianhuster** [comment]
Yes, I think that's an irrational fear. Your plugin can't be more dangerous than just running `:!playerctl some_args` from Nvim cmdline
